const Mobile = {
    // AUTH messages
    AUTH_SIGNUP: "Please check your email to confirm your account.",
    AUTH_LOGIN: "You Have Successfully Logged in to Frontdoor",
    AUTH_VERIFY: "Verify Successfully",
    AUTH_PASSWORD_SET: "Thanks, we've updated your password. Please login below to continue to your account.",
    AUTH_FORGET_PASSWORD: "Forget Password mail send successfully",
    AUTH_PASSWORD_NOT_MATCH: "Password did not match Please try again",
    AUTH_INVALID_TOKEN: "Invalid token",
    AUTH_INVALID_OTP: "The OTP you entered is invalid. Please enter the correct OTP",
    AUTH_OTP_NOT_VERIFY: "Verification failed please try again",
    AUTH_VERIFY_OTP: "OTP Verified Successfully",
    // USER Messages
    USER_ALREADY_EXIST: " A user with this email address already exists",
    USER_ALREADY_EXIST_AS_TEACHER: "This email already registered as a teacher",
    USER_NOT_EXIST: "The email you entered does not exist. Please check that you have typed your email correctly",
    USER_NOT_VERIFY: "You need to verify your email first",
    USER_PASSWORD_NOT_SET: "Please set password security for Login",
    USER_GET_SUCCESSFULLY: "User get successfully",
    USER_UPDATE_SUCCESSFULLY: "Updated successfully",
    USER_LIKE_GET: "Like List Get successfully",
    USER_FAVOURITE_GET: "Favourite List Get successfully",
    USER_BOOKMAEK_GET: "Bookmark List Get successfully",
    // Course Messages
    COURSE_ALREADY_EXIST: "This Course Alreaddy Exist",
    COURSE_NOT_EXIST: "Invalid Course Id",
    COURSE_ADD: "This course add successfully",
    COURSE_GET: "course get Successfully",
    COURSE_UPDATE: "course Update Sucessfully",
    COURSE_STATUS: "course Status Update Sucessfully",
    // Week Messages
    WEEK_ALREADY_EXIST: "This Week Alreaddy exist",
    WEEK_NOT_EXIST: "Invalid Week Id",
    WEEK_ADD: "This Week add successfully",
    WEEK_GET: "Week get Successfully",
    WEEK_UPDATE: "Week Update Sucessfully",
    // Lesson Messages
    LESSON_ALREADY_EXIST: "This lesson Alreaddy exist",
    LESSON_NOT_EXIST: "Invalid lesson Id",
    LESSON_ADD: "This lesson add successfully",
    LESSON_GET: "lesson get Successfully",
    LESSON_UPDATE: "lesson Update Sucessfully",
    LESSON_DELETE: "lesson delete Sucessfully",
    // Mission Messages
    MISSION_ALREADY_EXIST: "This mission Alreaddy exist",
    MISSION_NOT_EXIST: "Invalid mission Id",
    MISSION_ADD: "This mission add successfully",
    MISSION_GET: "mission get Successfully",
    MISSION_UPDATE: "mission Update Sucessfully",
    MISSION_DELETE: "mission delete Sucessfully",
    // Chapter Messages
    CHAPTER_ADD: "Chapter added successfully. ",
    CHAPTER_GET: "Chapter get Successfully",
    CHAPTER_NOT_EXIST: "Invalid Chapter Id",
    CHAPTER_UPDATE: "Chapter Update Sucessfully",
    CHAPTER_DELETE: "Chapter delete Sucessfully",
    CHAPTER_AWNSER_SOMETHING_WRONG: "Something wrong",
    CHAPTER_AWNSER_RIGHT: "Right Answer",
    CHAPTER_AWNSER_WRONG: "Wrong Answer",
    // Mission Content Messages
    MISSIONCONTENT_ADD: "Mission content added successfully. ",
    MISSIONCONTENT_GET: "Mission content get Successfully",
    MISSIONCONTENT_NOT_EXIST: "Invalid Mission content Id",
    MISSIONCONTENT_UPDATE: "Mission content Update Sucessfully",
    MISSIONCONTENT_DELETE: "Mission content delete Sucessfully",
    MISSIONCONTENT_RESTART: "Mission Restarted Sucessfully",
    MISSIONCONTENT_AWNSER_SOMETHING_WRONG: "Something wrong",
    MISSIONCONTENT_AWNSER_RIGHT: "Right Answer",
    MISSIONCONTENT_AWNSER_WRONG: "Wrong Answer",
    // Mission Content Messages
    POST_ADD: "Post added successfully. ",
    POST_GET: "Post get Successfully",
    POST_NOT_EXIST: "Invalid Post Id",
    POST_UPDATE: "Post Update Sucessfully",
    POST_DELETE: "Post delete Sucessfully",
    // Discussion
    DISCISSION_GET: "Discussion get successfully",
    ID_REQUIRE: "ID Require",
    REPLY_SENT: "Replyed successfully",
    // Like
    Like: "Like successfully",
    COMMENT: "Comment Add successfully",
}
module.exports = Mobile;